---

  - name: 3.2.1 - add all directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.all.accept_source_route = 0"
    tags:
      - level-1
      - section-3
      - "3.2.1"

  - name: 3.2.1 - add default directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.default.accept_source_route = 0"
    tags:
      - level-1
      - section-3
      - "3.2.1"

  - name: 3.2.1 Ensure packet redirect sending is disabled
    shell: "sysctl -w net.ipv4.conf.all.accept_source_route=0 && sysctl -w net.ipv4.conf.default.accept_source_route=0 && sysctl -w net.ipv4.route.flush=1"
    tags:
      - level-1
      - section-3
      - "3.2.1"

  - name: 3.2.2 - add all directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.all.accept_redirects=0"
    tags:
      - level-1
      - section-3
      - "3.2.2"

  - name: 3.2.2 - add default directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.default.accept_redirects=0"
    tags:
      - level-1
      - section-3
      - "3.2.2"
      
  - name: 3.2.2 Ensure packet redirect sending is disabled
    shell: "sysctl -w net.ipv4.conf.all.accept_redirects=0 && sysctl -w net.ipv4.conf.default.accept_redirects=0 && sysctl -w net.ipv4.route.flush=1"
    tags:
      - level-1
      - section-3
      - "3.2.2"

  - name: 3.2.3 - add all directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.all.secure_redirects=0"
    tags:
      - level-1
      - section-3
      - "3.2.3"

  - name: 3.2.3 - add default directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.default.secure_redirects=0"
    tags:
      - level-1
      - section-3
      - "3.2.3"
      
  - name: 3.2.3 Ensure packet redirect sending is disabled
    shell: "sysctl -w net.ipv4.conf.all.secure_redirects=0 && sysctl -w net.ipv4.conf.default.secure_redirects=0 && sysctl -w net.ipv4.route.flush=1"
    tags:
      - level-1
      - section-3
      - "3.2.3"

  - name: 3.2.4 - add all directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.all.log_martians=1"
    tags:
      - level-1
      - section-3
      - "3.2.4"

  - name: 3.2.4 - add default directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.default.log_martians=1"
    tags:
      - level-1
      - section-3
      - "3.2.4"

  - name: 3.2.4 Ensure packet redirect sending is disabled
    shell: "sysctl -w net.ipv4.conf.all.log_martians=1 && sysctl -w net.ipv4.conf.default.log_martians=1 && sysctl -w net.ipv4.route.flush=1"
    tags:
      - level-1
      - section-3
      - "3.2.4"

  - name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored)
    sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
    tags:
      - section3
      - section3.2
      - section3.2.5

  - name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored)
    sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
    tags:
      - section3
      - section3.2
      - section3.2.6

  - name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored)
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: 1
      state: present
    tags:
      - section3
      - section3.2
      - section3.2.7

  - name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored)
    sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
    when: enable_tcp_syncookies == True
    tags:
      - section3
      - section3.2
      - section3.2.8
