---

  - name: 3.1.1 Ensure IP forwarding is disabled (Scored)
    sysctl:
      name: net.ipv4.ip_forward
      value: '{{net_ipv4_ip_forward}}'
      state: present
    tags:
      - section3
      - section3.1
      - section3.1.1

  - name: 3.1.2 - add all directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.all.send_redirects=0"
    tags:
      - level-1
      - section-3
      - "3.1.2"

  - name: 3.1.2 - add default directly to file
    lineinfile:
      dest: "/etc/sysctl.conf"
      line: "net.ipv4.conf.default.send_redirects=0"
    tags:
      - level-1
      - section-3
      - "3.1.2"

  - name: 3.1.2 Ensure packet redirect sending is disabled
    shell: "sysctl -w net.ipv4.conf.all.send_redirects=0 && sysctl -w net.ipv4.conf.default.send_redirects=0 && sysctl -w net.ipv4.route.flush=1"
    tags:
      - level-1
      - section-3
      - "3.1.2"
