---

  # - name: 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured (Scored)
  #   file:
  #     path: /etc/ssh/sshd_config
  #     owner: root
  #     group: root
  #     mode: 0600
  #     state: file
  #   notify: restart ssh
  #   tags:
  #     - section5
  #     - section5.2
  #     - section5.2.1

  # - name: 5.2.2 Ensure SSH Protocol is set to 2 (Scored)
  #   lineinfile:
  #     dest: /etc/ssh/sshd_config
  #     regexp: '^Protocol'
  #     line: 'Protocol 2'
  #   notify: restart ssh
  #   tags:
  #     - section5
  #     - section5.2
  #     - section5.2.2

  - name: 5.2.3 Ensure SSH LogLevel is set to INFO (Scored)
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^LogLevel'
      line: 'LogLevel INFO'
    notify: restart ssh
    tags:
      - section5
      - section5.2
      - section5.2.3

  - name: 5.2.4 Ensure SSH X11 forwarding is disabled
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^X11Forwarding yes"
      line: "X11Forwarding no"
    tags:
      - level-1
      - section-5.2
      - "5.2.4"
    notify:
      - restart ssh

  - name: 5.2.5 Ensure SSH MaxAuthTries is set to 4 or less
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "MaxAuthTries 4"
    tags:
      - level-1
      - section-5.2
      - "5.2.5"
    notify:
      - restart ssh

  - name: 5.2.8 Ensure SSH root login is disabled
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin prohibit-password"
      line: "PermitRootLogin no"
    tags:
      - level-1
      - section-5.2
      - "5.2.8"
    notify:
      - restart ssh

  - name: 5.2.10 Ensure SSH PermitUserEnvironment is disabled
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "PermitUserEnvironment no"
    tags:
      - level-1
      - section-5.2
      - "5.2.10"
    notify:
      - restart ssh

  - name: 5.2.11 Ensure only approved MAC algorithms are used
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
    tags:
      - level-1
      - section-5.2
      - "5.2.11"
    notify:
      - restart ssh

  - name: 5.2.12 Ensure SSH Idle Timeout Interval is configured
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "ClientAliveInterval 300"
    tags:
      - level-1
      - section-5.2
      - "5.2.12"
    notify:
      - restart ssh

  - name: 5.2.12 Ensure SSH alive count is configured
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "ClientAliveCountMax 0"
    tags:
      - level-1
      - section-5.2
      - "5.2.12"
    notify:
      - restart ssh

  - name: 5.2.13 Ensure SSH LoginGraceTime is set to one minute or less
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^LoginGraceTime 120"
      line: "LoginGraceTime 60"
    tags:
      - level-1
      - section-5.2
      - "5.2.13"
    notify:
      - restart ssh

  - name: 5.2.14 Add allow users to ssh
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "AllowUsers ubuntu"
    tags:
      - level-1
      - section-5.2
      - "5.2.14"
    notify:
      - restart ssh

  - name: 5.2.15 Ensure SSH warning banner is configured
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "Banner /etc/issue.net"
    tags:
      - level-1
      - section-5.2
      - "5.2.15"
    notify:
      - restart ssh
