---

  - name: 1.3.1 Ensure AIDE is installed (Scored)
    apt:
      name: aide
      state: present
    register: aide_installed
    when: use_aide == True
    tags:
      - section1
      - section1.3
      - section1.3.1

  - name: 1.3.2 - Create cron entry to run aide filesystem integrity check regularly
    cron:
      name: "CIS 1.3.2 - Run aide filesystem integrity check"
      user: root
      job: "/usr/bin/aide --check"
      minute: 0
      hour: 5
      weekday: "*"
      day: "*"
      month: "*"
      state: present
    tags:
      - level-1
      - section-1
      - "1.3.2"
